apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      serviceAccountName: api-service-account
      volumes:
        - name: shared-data-volume
          persistentVolumeClaim:
            claimName: factory-shared-pvc
      containers:
      - name: api-server
        image: api-server:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: AAS_SERVER_URL
          value: "http://aas-mock-service:5001"
        volumeMounts:
          - name: shared-data-volume
            mountPath: /data # 컨테이너 내부의 /data 폴더에 연결
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api-server
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer